FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app
COPY . .
RUN dotnet publish HackathonHealthMed.GestaoConsultas/HackathonHealthMed.GestaoConsultas.csproj -c Release -o /out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /out .

EXPOSE 3004

ENTRYPOINT ["dotnet", "HackathonHealthMed.GestaoConsultas.dll"]