FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app
COPY . .
RUN dotnet publish HackathonHealthMed\HackathonHealthMed.Agendamentos -c Release -o /out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /out .

EXPOSE 3000 3001

ENTRYPOINT ["dotnet", "HackathonHealthMed.Agendamentos.dll"]