name: Docker Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Login no Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build & Push Autenticacao
      run: |
        docker build -f HackathonHealthMed/HackathonHealthMed.Autenticacao/Dockerfile.Autenticacao -t ${{ secrets.DOCKER_USERNAME }}/hackathonfiap-autenticacao:latest HackathonHealthMed
        docker push ${{ secrets.DOCKER_USERNAME }}/hackathonfiap-autenticacao:latest

    - name: Build & Push GestaoHorario
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/hackathonfiap-gestaohorario:latest ./HackathonHealthMed/HackathonHealthMed.GestaoHorario
        docker push ${{ secrets.DOCKER_USERNAME }}/hackathonfiap-gestaohorario:latest

    - name: Build & Push GestaoConsulta
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/hackathonfiap-gestaoconsultas:latest ./HackathonHealthMed/HackathonHealthMed.GestaoConsulta
        docker push ${{ secrets.DOCKER_USERNAME }}/hackathonfiap-gestaoconsultas:latest

    - name: Build & Push Agendamentos
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/hackathonfiap-agendamentos:latest ./HackathonHealthMed/HackathonHealthMed.Agendamentos
        docker push ${{ secrets.DOCKER_USERNAME }}/hackathonfiap-agendamentos:latest
